---
- name: clone
  git:
    repo: git@github.com:sugarcrm/stacks.git
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/stacks"
    update: no
    remote: upstream
- name: prereq
  command: bash ./prereq.sh
  become: true
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/stacks"
