---
- name: install
  homebrew_cask:
    name: vagrant
    accept_external_apps: yes
- name: ensure $HOME/.vagrant.d/
  file:
    path: "{{ lookup('env','HOME') }}/.vagrant.d"
    state: directory
    owner: "{{ lookup('env','USER') }}"
    group: staff
  become: true
- name: plugins
  command: vagrant plugin install {{ item }}
  loop:
    - vagrant-cachier
    - vagrant-vbguest
- name: vagrant completion
  homebrew:
    name: vagrant-completion
- name: vagrant manager
  homebrew_cask:
    name: vagrant-manager
    accept_external_apps: yes
