---
- name: clone
  git:
    repo: git@github.com:sugarcrm/Mango.git
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango"
    update: no
    remote: upstream
  register: cloned
- name: add origin
  command: git remote add origin git@github.com:{{ github_username }}/Mango.git
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango"
  when: cloned.before == None
- name: fetch origin
  command: git fetch origin
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango"
  when: cloned.before == None
  ignore_errors: yes
- name: initialize submodules
  command: git submodule init
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango"
  when: cloned.before == None
- name: update submodules
  command: git submodule update
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango"
  when: cloned.before == None
- name: composer install
  command: composer install
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/sugarcrm"
  when: cloned.before == None
- name: "sidecar : add remote for fork"
  command: git remote add {{ github_username }} git@github.com:{{ github_username }}/sidecar.git
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/sugarcrm/sidecar"
  when: cloned.before == None
- name: "sidecar : fetch fork"
  command: git fetch {{ github_username }}
  args:
    chdir: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/sugarcrm/sidecar"
  when: cloned.before == None
  ignore_errors: yes
- name: post-checkout hook
  copy:
    src: githook
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-checkout"
    mode: 0755
- name: ensure post-checkout.d/
  file:
    path: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-checkout.d"
    state: directory
    recurse: yes
- name: "post-checkout : update submodules"
  copy:
    src: submodule
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-checkout.d/submodule"
    mode: 0755
- name: post-merge hook
  copy:
    src: githook
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-merge"
    mode: 0755
- name: ensure post-merge.d/
  file:
    path: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-merge.d"
    state: directory
    recurse: yes
- name: "post-merge : update submodules"
  copy:
    src: submodule
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-merge.d/submodule"
    mode: 0755
- name: post-rebase hook
  copy:
    src: githook
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-rebase"
    mode: 0755
- name: ensure post-rebase.d/
  file:
    path: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-rebase.d"
    state: directory
    recurse: yes
- name: "post-rebase : update submodules"
  copy:
    src: submodule
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/post-rebase.d/submodule"
    mode: 0755
- name: pre-commit hook
  copy:
    src: githook
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/pre-commit"
    mode: 0755
- name: ensure pre-commit.d/
  file:
    path: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/pre-commit.d"
    state: directory
    recurse: yes
- name: "pre-commit : don't commit that error"
  copy:
    src: donotcommitthaterror
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/.git/hooks/pre-commit.d/donotcommitthaterror"
    mode: 0755
- name: config_si
  template:
    src: config_si.php.j2
    dest: "{{ lookup('env','HOME') }}/github.com/sugarcrm/Mango/sugarcrm/config_si.php"
