---
- name: install
  homebrew:
    name: "{{ item }}"
  loop:
    - reattach-to-user-namespace
    - tmux
# source: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/blob/master/Usage.md#basic-configuration
- name: configure
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.tmux.conf"
    create: yes
    line: set-option -g default-command "reattach-to-user-namespace -l zsh"
