---
- name: install
  copy:
    src: rome2stack
    dest: /usr/local/bin/rome2stack
    mode: 0755
- name: ensure $HOME/www/mango/
  file:
    path: "{{ lookup('env','HOME') }}/www/mango"
    state: directory
    recurse: yes
