---
# source: https://github.com/jwhitcraft/rome
- name: what is the operating system name?
  command: uname -s
  register: os_system_name
- name: what is the machine hardware name?
  command: uname -m
  register: machine_hardware_name
- name: install
  get_url:
    url: http://h2ik.co/rome/rome-{{ os_system_name.stdout }}-{{ machine_hardware_name.stdout }}
    dest: /usr/local/bin/rome
    mode: 0755
- name: self update
  command: /usr/local/bin/rome self-update
